// <auto-generated />
using System;
using GalleriesServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GalleriesServer.Data.Migrations
{
    [DbContext(typeof(GalleriesDbContext))]
    [Migration("20190118162531_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GalleriesServer.Models.MediaContainer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(2048);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int?>("OwnerID");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("MediaContainers");
                });

            modelBuilder.Entity("GalleriesServer.Models.MediaItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .HasMaxLength(2048);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int?>("MediaContainerID");

                    b.HasKey("ID");

                    b.HasIndex("MediaContainerID");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("GalleriesServer.Models.Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256);

                    b.Property<string>("ExternalIdentityProvider")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("FirstName")
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .HasMaxLength(256);

                    b.HasKey("ID");

                    b.HasIndex("ExternalUserId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("GalleriesServer.Models.MediaContainer", b =>
                {
                    b.HasOne("GalleriesServer.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerID");
                });

            modelBuilder.Entity("GalleriesServer.Models.MediaItem", b =>
                {
                    b.HasOne("GalleriesServer.Models.MediaContainer")
                        .WithMany("MediaItems")
                        .HasForeignKey("MediaContainerID");
                });
#pragma warning restore 612, 618
        }
    }
}
